Update ODIAC data content
US-GHG-Center/veda-config-ghg pull request #443
Opened 2024-07-18 20:13 UTC by paridhi-parajuli

## Why are you creating this Pull Request?

- Added minor content changes for [ODIAC](https://docs.google.com/document/d/1NLAyzK3BXrFK9T8eXI8KCw_QDevDQ4S5kf4Az0tUX28/edit)
- Changed the stac collection id to `odiac-ffco2-monthgrid-v2023`

2024-07-18 20:19 UTC, paridhi-parajuli commented
For now he exploration wont show up because the collection `odiac-ffco2-monthgrid-v2023` is only in the dev stac. For the exploration to work locally, change the api endpoints to `https://dev.ghg.center/api/*`

2024-07-19 16:52 UTC, Jeanne-le-Roux requested changes

2024-07-19 16:52 UTC, Jeanne-le-Roux commented on datasets/odiac-ffco2-monthgrid-v2023.data.mdx
>      Oda, Tomohiro., Maksyutov, Shamil. 2015. ODIAC Fossil Fuel CO₂ Emissions Dataset (Version name: ODIAC2022), Center for Global Environmental Research, National Institute for Environmental Studies,
Update the citation to the following:

Tomohiro Oda, Shamil Maksyutov, (2015). ODIAC Fossil Fuel CO2 Emissions Dataset (Version name: ODIAC2023), Center for Global Environmental Research, National Institute for Environmental Studies, [DOI:10.17595/20170411.001](http://doi.org/10.17595/20170411.001). (Reference date: 2024/07/15)

2024-08-02 16:05 UTC, slesaad commented
fix merge conflict and mark ready for review

2024-08-02 18:55 UTC, slesaad approved these changes

2024-08-02 19:35 UTC, Jeanne-le-Roux requested changes
Also ensure the Access Data > Data Browser link is updated (in the preview link it still points to v2022 data).

2024-08-02 19:35 UTC, Jeanne-le-Roux commented on datasets/odiac-ffco2-monthgrid-v2023.data.mdx
> +    Tomohiro Oda, Shamil Maksyutov, (2015). ODIAC Fossil Fuel CO2 Emissions Dataset (Version name: ODIAC2023), Center for Global Environmental Research, National Institute for Environmental Studies,
Hyperlink DOI:10.17595/20170411.001 with http://doi.org/10.17595/20170411.001

2024-08-02 19:35 UTC, Jeanne-le-Roux commented on datasets/odiac-ffco2-monthgrid-v2023.data.mdx
> +    The current dataset version is v2023, which replaced the v2022 dataset in the US GHG Center in June 2024. Summary of dataset update:
Change June to August

2024-08-02 19:35 UTC, Jeanne-le-Roux commented on datasets/odiac-ffco2-monthgrid-v2023.data.mdx
> +    - The year 2023 version of ODIAC is based on the latest country fossil fuel CO2 estimates (2000-2020) from the CDIAC team at the Appalachian State University, which includes an additional year of
Add subscript for CO2

2024-08-02 19:35 UTC, Jeanne-le-Roux commented on datasets/odiac-ffco2-monthgrid-v2023.data.mdx
> +    Tomohiro Oda, Shamil Maksyutov, (2015). ODIAC Fossil Fuel CO2 Emissions Dataset (Version name: ODIAC2023), Center for Global Environmental Research, National Institute for Environmental Studies,
Add subscript for CO2

2024-08-02 20:11 UTC, Jeanne-le-Roux approved these changes

2024-08-02 20:35 UTC, merged